language: cpp

matrix:
  include:
    - os: linux
      dist: focal
      sudo: required
      addons:
        apt:
          update: true
          packages:
            - g++-10
            - build-essential
            - cmake
            - libboost-all-dev

script:
  - bash scripts/build-c++.sh
